# Generated by Django 5.1.4 on 2025-01-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_persone_cv_personne_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='personne',
            managers=[
            ],
        ),
    ]
