# Generated by Django 5.1.4 on 2025-01-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_personne_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='telephone',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
